### PR TITLE
Add exec permissions to go-zip

### PR DESCRIPTION
**Pull request by ankitkumarr**
Fixes https://github.com/Azure/azure-functions-core-tools/issues/1793

### CODE REVIEW

**Comment by ahmelsayed** [comment]
do you wanna up the version number of the package so users get offered an update? you can just ++ it.

**Comment by ankitkumarr** [comment]
do you mean a full release with a new version, or just the version here in the Formula? Just Formula version here would create a mismatch, and I am not sure if there's any repercussion to that.

**Comment by ahmelsayed** [comment]
I was thinking just the formula version. I thought that's only used by brew client to figure out if it needs to update or not. But it's a good point. I don't have a mac to verify it. Maybe we can give the people affected a workaround of running `chmod +x` manually

**Comment by ankitkumarr** [comment]
Also looks like we'd need to do this for linux packages as well. I will get a PR for that. That'd would need a release of the packages itself I imagine.

**Comment by ankitkumarr** [comment]
@ahmelsayed, I will do a release tonight / tomorrow. In the meantime, should we also just merge this (if you can approve)? As this will at least start helping new downloads right away,

**Pull request merged**
