### PR TITLE
Added support for osx-arm64

### PR DESCRIPTION
**Pull request by orrpan**

### CODE REVIEW

**Comment by ejizba** [comment]
Thanks for the contribution, @orrpan, but I plan to do this myself in a slightly different way. I will be updating some scripts/build steps at the same time I add support for arm64 (similar to this PR here: https://github.com/Azure/homebrew-functions/pull/96)

I'm just waiting to do that because I was working on signing arm64 binaries first. If we don't sign the binaries, any command you run will just silently fail
- A comment about it here: https://github.com/Azure/azure-functions-core-tools/issues/2834#issuecomment-1102927470
- A blog post about how Apple requires arm64 executables to be signed: https://eclecticlight.co/2020/08/22/apple-silicon-macs-will-require-signed-code/
- My PR that was recently merged here (just hasn't been released yet): https://github.com/Azure/azure-functions-core-tools/pull/3033

**Comment by ejizba** [comment]
Thanks for the contribution, @orrpan, but I plan to do this myself in a slightly different way. I will be updating some scripts/build steps at the same time I add support for arm64 (similar to this PR here: https://github.com/Azure/homebrew-functions/pull/96)

I'm just waiting to do that because I was working on signing arm64 binaries first. If we don't sign the binaries, any command you run will just silently fail
- A comment about it here: https://github.com/Azure/azure-functions-core-tools/issues/2834#issuecomment-1102927470
- A blog post about how Apple requires arm64 executables to be signed: https://eclecticlight.co/2020/08/22/apple-silicon-macs-will-require-signed-code/
- My PR that was recently merged here (just hasn't been released yet): https://github.com/Azure/azure-functions-core-tools/pull/3033

**Comment by ahgraber** [comment]
Is there an ETA for this release?  Thanks!

**Comment by ejizba** [comment]
Closing in favor of https://github.com/Azure/homebrew-functions/pull/103

In terms of ETA, we're just waiting for the next regularly scheduled release of core tools to pick up the signing changes. Should be in the next few weeks

**Comment by ejizba** [comment]
Hi @orrpan @ahgraber just fyi we merged ARM support for brew in the other PR

**Pull request closed without merging**
