### PR TITLE
Updating core tools to 3.0.3568

### PR DESCRIPTION
**Pull request by azfuncgh**

### CODE REVIEW

**Comment by sceniclife** [comment]
Hello, is there an eta for this to be merged?

**Comment by dolphinspired** [comment]
It's been about 3 months... is this going to get merged, or should I move on to some other method for installing core tools?

**Comment by dolphinspired** [comment]
@ahmelsayed @ankitkumarr @yojagad Anyone watching this repo?

**Comment by kroussou** [comment]
@soninaren Looks like this PR is outdated and may be closed
CC: @ahmelsayed @ankitkumarr @yojagad

**Pull request closed without merging**
